Connected.oledClear()
notLegos.potSet(AnalogPin.P1)
notLegos.mp3setPorts(SerialPin.P14)
notLegos.mp3setPorts(SerialPin.P16)
notLegos.setSounds("Mario")
basic.pause(notLegos.playsFor(notLegos.getSoundString("SFX", "Splash")))
basic.pause(notLegos.playsFor(notLegos.getSoundString("Player", "Yay")))
basic.pause(notLegos.playsFor(notLegos.getSoundString("Music", "Level")))
